# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  unit-tests:
    docker:
      - image:  circleci/golang:1.13
    working_directory: ~/repo
    steps:
      - checkout
      - run: go test .
  e2e-tests:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/repo/artifacts
      - run:
          name: Run API in background
          command: ~/repo/artifacts/server
          background: true
      - run: curl localhost:8080/greetings
      - run: go test ./tests/...
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/repo
    steps:
      - checkout
      - run: mkdir artifacts
      - run: go build -o artifacts/server main.go
      - run: chmod +x artifacts/server
      - persist_to_workspace:
          root: artifacts
          paths:
            - server
  deploy:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "00:59:75:e0:30:7c:67:60:46:7d:ce:78:c6:6b:62:9d"
      - attach_workspace:
          at: /home/circleci/repo
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan 163.172.6.169 >> ~/.ssh/known_hosts
      - run: scp server flint@163.172.6.169:/home/flint/my-server
workflows:
  version: 2
  deploy:
    jobs:
      - build
      - unit-tests
      - e2e-tests:
          requires:
            - build
      - deploy:
          requires:
            - build
            - e2e-tests
            - unit-tests
