# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  unit-tests:
    docker:
      - image:  circleci/golang:1.13
    working_directory: ~/repo
    steps:
      - checkout
      - run: go test .
  e2e-tests:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt install -y screen
      - run: go build -o server main.go
      - run: chmod +x server
      - run: TERM='vt100' screen -d -m ~/repo/server
      - run: sleep 2
      - run: curl localhost:8080/greetings
      - run: go test ./tests/...
  # build:
  #   docker:
  #     - image: circleci/golang:1.13
  #   working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  #   steps:
  #     - checkout
  #     - 
      # - run: go test -v ./...

workflows:
  version: 2
  deploy:
    jobs:
      - unit-tests
      - e2e-tests